apiVersion: v1
kind: Service
metadata:
  annotations:
    service.beta.kubernetes.io/azure-dns-label-name: fgraph
  labels:
    io.kompose.service: graph-analysis
  name: graph-analysis
spec:
  ports:
  - name: "5000"
    port: 5000
    targetPort: 5000
  selector:
    io.kompose.service: graph-analysis
spec:
  type: LoadBalancer
  ports:
  - name: "5000"
    port: 5000
  selector:
    io.kompose.service: graph-analysis
