apiVersion: v1
kind: ConfigMap
metadata:
  name: kafka-hq-config
  labels:
    app: kafka-hq
data:
  application.yml: |-
    akhq:
           server:
                  base-path: "/kafkahq"
           # list of kafka cluster available for kafkahq
           connections:
                  fandango-kafka: # url friendly name for the cluster (letter, number, _, -, ... dot are not allowed here)
                    properties: # standard kafka properties (optional)
                           bootstrap.servers: "fandangoedge02:9092"

           # Auth & Roles
           security:

             # default-roles:
             #  - topic/read

             default-group: no-roles # Default groups for all the user even unlogged user (no-roles is a group created by default)

             # Groups definition
             groups:
               admin: # Group name
                 roles:  # roles for the group
                   - topic/read
                   - topic/insert
                   - topic/delete
                   - topic/config/update
                   - node/read
                   - node/config/update
                   - topic/data/read
                   - topic/data/insert
                   - topic/data/delete
                   - group/read
                   - group/delete
                   - group/offsets/update
                   - registry/read
                   - registry/insert
                   - registry/update
                   - registry/delete
                   - registry/version/delete
                   - acls/read
                   - connect/read
                   - connect/insert
                   - connect/update
                   - connect/delete
                   - connect/state/update
               
               partner: # Other group
                 roles:
                    - topic/data/read
                    - topic/data/insert
                    - topic/data/delete
                    - group/read
                    - topic/read
                    - topic/insert
                    - topic/delete
                    - registry/read

             
             basic-auth:
               admin: # Username
                 password: c6ba530b2259cdc06dd954ada79e7a43df52517892ca0e1210bbb0656667b3e2 # Password in sha256
                 groups: # Groups for the user
                   - admin
 
               fandango-partner:
                 password: 468230bcc7378dccc4d7c5ab822741784ef9304efc354d0831f101999ab65079 # Password in sha256
                 groups: # Groups for the user
                   - partner


    micronaut:
      server:
        port: 9001
      security:
        enabled: true

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-hq
  labels:
    app: kafka-hq
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka-hq
  template:
    metadata:
      labels:
        app: kafka-hq
    spec:
      containers:
        - name: kafka-hq
          image: tchiotludo/akhq:0.14.1
          ports:
          - containerPort: 9001
            name: http
            protocol: TCP
          resources:
            limits:
              memory: 512Mi
            requests:
              memory: 256Mi
          volumeMounts:
            - mountPath: /app/application.yml
              subPath: application.yml
              name: config
              readOnly: true
      volumes:
        - name: config
          configMap:
            name: kafka-hq-config

---
apiVersion: v1
kind: Service
metadata:
  annotations:
    service.beta.kubernetes.io/azure-dns-label-name: fkafkahq
  name: kafka-hq
  labels:
    app: kafka-hq   
spec:
  type: LoadBalancer
  ports:
    - name: http
      port: 9001
      protocol: TCP
      targetPort: 9001
  selector:
    app: kafka-hq
