apiVersion: v1
kind: Service
metadata:
  annotations:
    service.beta.kubernetes.io/azure-dns-label-name: fpreprocessing
  creationTimestamp: null
  labels:
    io.kompose.service: preprocessing
  name: preprocessing
spec:
  type: LoadBalancer
  ports:
  - name: "5001"
    port: 5001
    targetPort: 5001
  selector:
    io.kompose.service: preprocessing

